apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.22.3
    helm:
      values: | 
        mixer:
          policy:
            enabled: true
        global:
          disablePolicyChecks: false
        meshConfig:
          outboundTrafficPolicy:
            mode: ALLOW_ANY
          mixer:
            policy:
              enabled: true
          global:
            disablePolicyChecks: false

  destination:
    server: 'https://34.126.151.196'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  dependsOn:
    - istio-base

