apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealedsecret-test
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sealedsecret-test
  template:
    metadata:
      labels:
        app: sealedsecret-test
    spec:
      containers:
      - name: sealedsecret-test
        image: busybox
        command: ["sh", "-c", "while true; do sleep 3600; done"]
        env:
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: appsecret
              key: apikey
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      restartPolicy: Always

