---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgAEbRgVHLQVTIf3TcbfFinekFP+UpIC1/rkIdmWYS0G/OsvWpsHLx8YRm86v/rRdsfBMPsgU/bEyAfDZxGKaeFueFskUkaaravMmyhg39PbPd2KBNmMku5U2PRydz3qmwypHfL4/wTbUuFsgmS71Eaw1j0QL/peM39qYmfYoUG0fcuDpLuSFCxck9Uo3TqE9LccvAhqMRW2SYpg798pcd+VSivR6rsK09a/x3aC1fxXLHrTw6WcK0+5FNo6zb4x+xpWHF6eAqJ66BYQI2h7s3RQcyfpxCFrxJ9nSJ5yil1+sHrykHGffYxm0lE1Oe3XGZSVY++wmgiC4pCoLVBNE5P+7mIMcAnQyy6J5AAvcGSxXeQQhIqeqFrl28dJIRq4KCIykYGm/vPW2J067lQ0H/jYs6cnEzkrlDTyJCSi4umQHMIcs7g0rHmAWf0DTJbH8zEVK18dHQLm676H8pohU+OoWhRghOpulpQusopayY+nlLhmlywK3RnXVWmkPbfPVaQdk4ErZ5f2cM0/Kqnc4gfE6luF8dqu4bzNVCfFEI3UbAI365ckb/izui1CcUQ2mCBhtFVXfMfnqcH9FxfFlrGvg+1K0yNUFbStmJ/MCi7sv67cv5bEl/sdBFv5p0QYdDcwykzHz/++5q8OCtXJP61jnmnsC02Vq4CbPM8wN4YLw2VObOTTDvuqbtNvggiDUlSojGKCDXqUBsLvSdWyMVoQT7j140Gwq3kSskxSGONXe/3WbuYTqkFgiw==
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
