apiVersion: v1
kind: Service
metadata:
  name: product-microservice-nodejs-service
spec:
  selector:
    app: product-microservice-nodejs
  ports:
  - port: 80
    targetPort: 3000
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-microservice-nodejs-deployment
spec:
  selector:
    matchLabels:
      app: product-microservice-nodejs
  template:
    metadata:
      labels:
        app: product-microservice-nodejs
    spec:
      containers:
      - name: product-microservice-nodejs
        image: ivplay4689/product-microservice-nodejs:v1
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
        env:
          - name: PRODUCT_YAML_PATH
            value: "/etc/config/products.yaml"
        volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: product-microservice-nodejs-config
--- 

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product-microservice-nodejs-hpa
  namespace: default
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-microservice-nodejs-deployment
  targetCPUUtilizationPercentage: 50
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-microservice-nodejs-config
data:
  products.yaml: |
    products:
      - id: 1
        name: "Laptop"
        category: "Electronics"
        price: 999.99
        stock: 20
        description: "A high-performance laptop suitable for all your computing needs."
        features:
          - "Intel Core i7 Processor"
          - "16GB RAM"
          - "512GB SSD"
          - "15.6 inch Full HD Display"
        images:
          - "https://example.com/images/laptop1.jpg"
          - "https://example.com/images/laptop2.jpg"

      - id: 2
        name: "Smartphone"
        category: "Electronics"
        price: 599.99
        stock: 50
        description: "A cutting-edge smartphone with all the latest features."
        features:
          - "6.5 inch OLED Display"
          - "128GB Storage"
          - "Triple Camera System"
          - "5G Connectivity"
        images:
          - "https://example.com/images/smartphone1.jpg"
          - "https://example.com/images/smartphone2.jpg"

