apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  components:
    prometheus:
      enabled: true
    tracing:
      enabled: true
    kiali:
      enabled: true
    grafana:
      enabled: true
  values:
    telemetry:
      v2:
        enabled: true
        prometheus:
          enabled: true
        tracing:
          enabled: true
