
# This manifest file dictates how the applications should be deployed
apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: argocd
  namespace: argocd 
spec:
  project: default 
  source:
    repoURL: 'https://github.com/mdnajimahmed/LocalSystem.git' 
    path: argocd/argo-cd/applications # argocd/argo-cd/applications
    targetRevision: main 
  destination:
    server: 'https://34.126.151.196' #
    namespace: argocd # Must be argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true 
