apiVersion: apps/v1
kind: Deployment
metadata:
  name: shellz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shellz
  template:
    metadata:
      labels:
        app: shellz
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "while true; do sleep 3600; done"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      - name: curl
        image: curlimages/curl:8.9.1
        command: ["sh", "-c", "while true; do sleep 3600; done"]
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
          requests:
            memory: "256Mi"
            cpu: "100m"
      - name: fortio
        image: fortio/fortio:latest_release
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-fortio
        - containerPort: 8079
          name: grpc-ping
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
          requests:
            memory: "256Mi"
            cpu: "100m"
# --- 


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: httpbin
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: httpbin
#   template:
#     metadata:
#       labels:
#         app: httpbin
#     spec:
#       containers:
#       - name: httpbin
#         image: docker.io/kong/httpbin
#         imagePullPolicy: IfNotPresent
#         # Same as found in Dockerfile's CMD but using an unprivileged port
#         command:
#         - gunicorn
#         - -b
#         - "[::]:9090"
#         - httpbin:app
#         - -k
#         - gevent
#         env:
#         # Tells pipenv to use a writable directory instead of $HOME
#         - name: WORKON_HOME
#           value: /tmp
#         ports:
#         - containerPort: 9090
#         resources:
#           limits:
#             memory: "256Mi"
#             cpu: "100m"
#           requests:
#             memory: "256Mi"
#             cpu: "100m"
# --- 
# apiVersion: v1
# kind: Service
# metadata:
#   name: httpbin
#   labels:
#     app: httpbin
# spec:
#   ports:
#   - name: http
#     port: 8000
#     targetPort: 9090
#   selector:
#     app: httpbin
# --- 
