apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example
spec:
  server:
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
    route:
      enabled: true
  applicationSet:
    resources:
      limits:
        cpu: 50m
      memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
  repo:
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
  dex:
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
  redis:
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
  controller:
    resources:
      limits:
        cpu: 550m
        memory: 1Gi
      requests:
        cpu: 550m
        memory: 1Gi