apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-microservice-v1
spec:
  selector:
    matchLabels:
      app: payment-microservice
  template:
    metadata:
      labels:
        app: payment-microservice
    spec:
      containers:
      - name: payment-microservice
        image: ivplay4689/payment-microservice-nodejs
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
        env:
         - name: PAYMENT_APP_VERSION
           value: "1.0.0"
          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-microservice-v2
spec:
  selector:
    matchLabels:
      app: payment-microservice
  template:
    metadata:
      labels:
        app: payment-microservice
        
    spec:
      containers:
      - name: payment-microservice
        image: ivplay4689/payment-microservice-nodejs
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
        env:
         - name: PAYMENT_APP_VERSION
           value: "1.0.1"
          
---
apiVersion: v1
kind: Service
metadata:
  name: payment-microservice
spec:
  selector:
    app: payment-microservice
  ports:
  - port: 80
    targetPort: 3000
